[project]
name = "normalize-bundler"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.operator-registry]
path = "contracts/operator-registry.clar"
depends_on = []

[contracts.bundle-manager]
path = "contracts/bundle-manager.clar"
depends_on = []

[contracts.resource-tracker]
path = "contracts/resource-tracker.clar"
depends_on = []

[contracts.maintenance-tracker]
path = "contracts/maintenance-tracker.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
